Basic structure
Lordkaito/to-do-list pull request #1
Opened 2021-09-21 19:14 UTC by Lordkaito

In this branch:
1. Set webpack to work with my project.
2. Added basic HTML and CSS that will be modified later dynamically.
3. Added basic js to add content to my page.

2021-09-21 20:01 UTC, Dipeshtwis requested changes
Hi @Lordkaito, 

:+1: This is good to make it this far, your project is really nice, congratulations on the good work you have done so far.
:+1: The project has an array of simple to-do tasks.

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!


 ## Required Changes ♻️

**_Check the comments under the review_**

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

- N.A.

Cheers and Happy coding!👏👏👏
Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

**_Dipesh Kumar_**


------

_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project(check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-09-22 11:37 UTC, rloterh commented on README.md
> +
This issue is well resolved! ✔️

2021-09-22 11:43 UTC, rloterh commented on src/style.css
> +  display: flex;
This issue is well resolved! ✔️

2021-09-22 11:43 UTC, rloterh commented on src/index.js
> +// import _ from 'lodash';
This issue is well resolved! ✔️

2021-09-22 11:44 UTC, rloterh approved these changes

2021-09-22 11:46 UTC, rloterh approved these changes
## Status: Approved :heavy_check_mark:

Hi Isaí, 

Your project is complete! Great job for making the necessary changes recommended by the previous reviewer(s). There is nothing else to say other than... it's time to merge it 🍾:shipit:.
Congratulations! 🎉🥂


Cheers and Happy coding!👏 💻 🍷 

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have 1 more limited review per this project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-09-22 11:49 UTC, merged